### ISSUE TITLE
User should be able to link their Discord ID

### ISSUE THREAD

**Issue by zkldi** [TNG-dev/tachi-bot#21]
We need a way of storing discordID -> apiKey mappings.

An in-JS solution wont work because if the server powers off we're screwed. A simple key value storage thing will do though, maybe we could just use redis?

Do we need anything more powerful like mongo? I don't know :P

**Comment by Puffycheeses** [comment]
Mongo would be nice but really comes down to the server and how much resources we wanna use. 
Even flat-file could work since its just 1:1 relationships between strings? Maybe worth investigating before jump on this one. 
Store in memory for now? just while testing?

**Comment by zkldi** [comment]
In memory is fine for testing yeah. Mongo is nice but I'm more concerned about whether we need any of it. Flatfile is a bit too hacky imo.
