### ISSUE TITLE
Test Framework

### ISSUE THREAD

**Issue by zkldi** [TNG-dev/tachi-bot#25]
At the moment, everything is untested. We could set up a test framework?

I'm personally partial to [Node Tap](https://node-tap.org), but really anything sane is aight.

**Comment by Puffycheeses** [comment]
Jest is already in the repo since this is a fork of my music bot. It's just none of the tests could come over (Since they all music related)

I'm happy swapping to Tap 👍, basically comes down to whoever writes the first tests lol

**Comment by zkldi** [comment]
Sounds like a good opportunity for me to try out jest :P

**Comment by zkldi** [comment]
Not sure I care enough to write tests for this, given that a lot of it is tightly coupled with discord. Probably not.

**Comment by zkldi** [comment]
I've decided I don't care about automated testing for this project -- it's too tightly coupled and not crucial to tachi. If anyone wants to do it for me, be my guest.
