### ISSUE TITLE
Class Updates should render conditionally.

### ISSUE THREAD

**Issue by zkldi** [TNG-dev/tachi-bot#49]
Things like users rapidly climbing classes due to things like SDVX's class system or CHUNITHM's colour system results in spam in the chat.

Since these games are (up to N best scores) / N where N is a constant, we should not render class achievements in these contexts where the user has less than N scores.

**Comment by zkldi** [comment]
Fixed in 2.1.

**Comment by cg505** [comment]
it's minor but I think the logic as implemented ignores the case where you play the same chart multiple times, since we technically care about the number of PBs, not overall scores

**Comment by zkldi** [comment]
oog

**Comment by zkldi** [comment]
I've decided I don't care. This is a rough stopgap measure to stop spam, and can't handle more complex cases like how if a user has 50 plays on "HOT" charts but no plays on not-hot charts and therefore spams anyway.
