### ISSUE TITLE
Add CI/CD 

### ISSUE THREAD

**Issue by pfych** [TNG-dev/tachi-bot#9]
When a push is made to the `main` branch the bot should auto-deploy to the server.

The following secrets need to be set up on the repo:
```
ENV=PROD
PROD_DISCORD_TOKEN=discordToken
```

These env vars are used by `createEnv.sh` to generate the bots environment file. When pushing the bot to the server ensure you run this script beforehand and also push the generated `.env` file

This ticket is blocked until #10 is merged

**Comment by Puffycheeses** [comment]
@zkldi Could you assign this to the relevant person?

**Comment by zkldi** [comment]
Done!

**Comment by Puffycheeses** [comment]
Updated the ticket with a bit more info 👍

**Comment by zkldi** [comment]
We'll also need to configure some more environment variables and a conf.json5 file.

We'll need `PROD_BOT_CLIENT_ID` and `PROD_BOT_CLIENT_SECRET` aswell in the env, and a nice conf.json5 to go with it. Currently this is documented inline.

**Comment by ereti** [comment]
I don't really understand the setup at the moment. Your npm/pnpm/yarn/whatever "start" command (using ts-node) is untenable. The process of building should involve a compilation step, and then the code will be executed with node as normal. This will be done in a Dockerfile. I can handle that, obviously, I just don't understand how to reconcile that and the current setup. The 'createEnv.sh' script also seems pointless given this - I can run it in the Dockerfile, but... why not just provide those environment variables in (e.g.) docker-compose?

**Comment by pfych** [comment]
Next week when I start working on this again I’ll jump in a call/DMs with you. Was unaware you were running everything in docker. 👍

There’s lots of work that needs doing.
